import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import ThemeSwitch from '@/components/themeswitch'
import ThemeContextProvider from '@/context/themecontext'
import NavBar from '@/components/navbar/navbar'
import RegisterModal from '@/components/modals/registermodal'
import ToasterProvider from '@/context/toasterprovider'
import LoginModal from '@/components/modals/loginmodal'
import UserContextProvider from '@/context/usercontext'
import getCurrentUser from '@/actions/getCurrentUser'
import RentModal from '@/components/modals/rentmodal'
import SearchModal from '@/components/modals/searchmodal'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();
  return (
    <ThemeContextProvider>
      <UserContextProvider getUser={currentUser}>
      <html lang="en">
        <body className={`${inter.className} bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100`}>
          <NavBar />
          <RentModal />
          <RegisterModal/> 
          <LoginModal />
          <SearchModal />
          <div className="pb-20 pt-28">
          {children}
          </div>
          <ThemeSwitch />
          <ToasterProvider />
        </body>
      </html>
      </UserContextProvider>
    </ThemeContextProvider>
  )
}
